### ISSUE TITLE
Developing bi-directional application

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#158]
**"The bigger picture":**
As we're developing an infrastructure, there is significance to a convenient API to the applications' developer. In addition, as part of the changes to our system which allow bi-directional sensors, we will need an application to test them.

**TODO:**

- [x] get to know the applications' API.
- [x] start working on a new application, which will use the bi-directional sensors.

**Comment by alexvitho** [comment]
Added a new Shutters sensor with basic GUI.
Next step is run it with the application.

**Comment by RonGatenio** [comment]
@alexvitho 
In order to continue your work on the sensor and app, do:
`git checkout old_sensors_com`
on this branch the sensors still communicate with the house:

![vitals](https://cloud.githubusercontent.com/assets/15971916/26037680/411a4b4a-3901-11e7-8c12-383ad6e4a826.gif)

Note that if the applications don't load:
```
Initializing system ui...
Initializing system components...
Exception in thread "main" il.ac.technion.cs.smarthouse.system.exceptions.SensorNotFoundException: Sensor with ID: COMM_NAME was not found
	at il.ac.technion.cs.smarthouse.system.services.sensors_service.SensorsManager.getAllSensors(SensorsManager.java:47)
	at il.ac.technion.cs.smarthouse.system.services.sensors_service.SensorsManager.getDefaultSensor(SensorsManager.java:70)
	at il.ac.technion.cs.smarthouse.applications.vitals.VitalsApp.onLoad(VitalsApp.java:36)
	at il.ac.technion.cs.smarthouse.system.applications.ApplicationManager.initialize(ApplicationManager.java:57)
	at il.ac.technion.cs.smarthouse.system.applications.ApplicationsCore.initializeApplicationManager(ApplicationsCore.java:64)
	at il.ac.technion.cs.smarthouse.system.applications.ApplicationsCore.addApplication(ApplicationsCore.java:40)
	at il.ac.technion.cs.smarthouse.system.applications.api.SmartHouseApplication.launch(SmartHouseApplication.java:49)
	at il.ac.technion.cs.smarthouse.applications.vitals.VitalsApp.main(VitalsApp.java:27)
```

You will need to change one parameter: bbc5857544a64b64b7d2884580f86acafaef5773

**Comment by alexvitho** [comment]
Woow!! @RonGatenio  R.E.S.P.E.C.T. !!
T.Y.

**Comment by alexvitho** [comment]
bidirectional connection support. Issue: #137

**Comment by EliaTraore** [comment]
Since this app has been discontinued, this issue can be closed.
