### ISSUE TITLE
Dashboard: widget add bug

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/Smartcity-Smarthouse#217]
I get this exception when trying to add a widget of type Graph:
```
java.lang.NullPointerException
	at eu.hansolo.tilesfx.skins.SparkLineTileSkin.initGraphics(SparkLineTileSkin.java:131)
	at eu.hansolo.tilesfx.skins.TileSkin.<init>(TileSkin.java:105)
	at eu.hansolo.tilesfx.skins.SparkLineTileSkin.<init>(SparkLineTileSkin.java:93)
	at eu.hansolo.tilesfx.Tile.createDefaultSkin(Tile.java:4095)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

To re-create this:
- Open the Smarthouse in User Mode
- Move the pulse slider in the Vitals sensor
- Click on the Dashboard tab
- Click the +
- Choose graph widget
- Click on the SparkLine tile (the leftmost)
- Choose pulse as the path
- Type "pulse" as the name
- Click "Add"
- Click "OK"

**Comment by ylevv** [comment]
I also get this exception when trying to add a widget of Percentage type:
```
java.lang.NullPointerException
	at eu.hansolo.tilesfx.skins.HighLowTileSkin.initGraphics(HighLowTileSkin.java:97)
	at eu.hansolo.tilesfx.skins.TileSkin.<init>(TileSkin.java:105)
	at eu.hansolo.tilesfx.skins.HighLowTileSkin.<init>(HighLowTileSkin.java:73)
	at eu.hansolo.tilesfx.Tile.createDefaultSkin(Tile.java:4091)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```
To re-create this:
- Open the Smarthouse in User Mode
- Move the pulse slider in the Vitals sensor
- Click on the Dashboard tab
- Click the +
- Choose percentage widget
- Click on the percentage tile
- Choose pulse as the path
- Type "pulse" as the name
- Click "Add"
- Click "OK"

**Comment by inbalzukerman** [comment]
I have no idea why my commit closed this issue 😨

**Comment by inbalzukerman** [comment]
Fyi, apparently using the word "fixed" in a commit message automatically close the issue referenced afterwards!

**Comment by EliaTraore** [comment]
NVM, just duplicate work (why solve a bug once when you can solve it twice? lol)
