### ISSUE TITLE
Exception when running the app (newest release)

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Smartcity-Smarthouse#247]
![image](https://user-images.githubusercontent.com/22842727/27769237-6c4c4144-5f2e-11e7-9bc4-5d157ccdbe27.png)

**Comment by roy-shchory** [comment]
its a known bug use try to recover and it will continue working

**Comment by RonGatenio** [comment]
Can you please send us the log reports (can be found in the Logs folder that was created in the same directory as the JAR)

**Comment by AnnaBel7** [comment]
@RonGatenio 
[log.log.zip](https://github.com/TechnionYP5777/Smartcity-Smarthouse/files/1117755/log.log.zip)

I reopened the app a few times since, so maybe it won't show

**Comment by RonGatenio** [comment]
Saving this here, I will fix this later, Thanks!
```
2017-07-02 13:56:00 ERROR [Thread-21] failure_detector.SystemFailureDetector#logException (SystemFailureDetector.java:52) - 
	Uncaught exception from thread [Thread-21]
	Exception:
	java.util.ConcurrentModificationException
	Cause:
	java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at il.ac.technion.cs.smarthouse.system.services.sensors_service.SensorApiImpl.searchForSensorId(SensorApiImpl.java:205)
	at il.ac.technion.cs.smarthouse.system.services.sensors_service.SensorApiImpl.lambda$searchForSensorId$86(SensorApiImpl.java:240)
	at il.ac.technion.cs.smarthouse.system.file_system.EventHandler.accept(FileSystemImpl.java:387)
	at il.ac.technion.cs.smarthouse.system.file_system.FileSystemImpl.sendMessage(FileSystemImpl.java:243)
	at il.ac.technion.cs.smarthouse.system.sensors.SensorDataRecevierThread.handleRegisterMessage(SensorDataRecevierThread.java:60)
	at il.ac.technion.cs.smarthouse.system.sensors.SensorDataRecevierThread.handleSensorMessage(SensorDataRecevierThread.java:45)
	at il.ac.technion.cs.smarthouse.system.sensors.SensorManagingThread.run(SensorManagingThread.java:76)
```

**Comment by RonGatenio** [comment]
This is some kind of an heisenbug. I think I fixed it in the [new release](https://github.com/TechnionYP5777/Smartcity-Smarthouse/releases/latest)
