### ISSUE TITLE
Exception when trying to add a widget

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Smartcity-Smarthouse#251]
![image](https://user-images.githubusercontent.com/22842727/27769457-06dc783e-5f32-11e7-876d-a7359112b852.png)

**Comment by RonGatenio** [comment]
Very weird... can you send us the report (by clicking `Send Report`), or by sending us the Logs

**Comment by AnnaBel7** [comment]
@RonGatenio 
I sent a report.

**Comment by EliaTraore** [comment]
@RonGatenio 
We received the following stack track - 
```java
Stack Trace:
java.lang.NullPointerException
        at il.ac.technion.cs.smarthouse.gui.controllers.dashboard.DashboardController.lambda$openConfigWindow$111(DashboardController.java:99)
        at il.ac.technion.cs.smarthouse.gui.controllers.dashboard.ConfigController.lambda$null$73(ConfigController.java:308)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

```
